# Generated by Django 6.0.2 on 2026-03-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="driver",
            new_name="drivers",
        ),
    ]
