# Generated by Django 6.0.3 on 2026-03-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_rename_driver_car_drivers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="email",
            field=models.CharField(max_length=100),
        ),
    ]
